In [2]:
#Importar librerias 

import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [3]:
#Cargar desde un archivo .csv sin indice
df = pd.read_csv("Rio de Janeiro.csv", encoding="latin1")
df

,id,last_scraped,name,description,neighborhood_overview,picture_url,host_name,host_since,host_about,host_response_time,...,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,reviews_per_month
0,2.806250e+05,25/09/2024,"Fascinating Rio, on the hills!",NaN,NaN,https://a0.muscache.com/pictures/3455893/00487...,Marcia Longras,09/04/2011,"I'm a Brazilian lady, I was born in Rio de Jan...",within a few hours,...,4.69,4.82,4.58,4.73,4.85,4.64,4.64,NaN,f,0.22
1,2.807650e+05,25/09/2024,STUDIO RIO LAPA CARNIVAL,"The studio is in an excellent location , dire...",NaN,https://a0.muscache.com/pictures/2991089/4bfbb...,Erika,02/12/2011,"Sou Erika tenho 37 anos ,casada, formada em ...",within a day,...,4.67,5.00,4.00,4.67,5.00,4.67,4.67,NaN,f,0.02
2,2.813040e+05,26/09/2024,"5 min a pÃ© - Praia de Copacabana, MetrÃ´, WiFi I","Bedroom and living room, with a private bathro...",We are in Copacabana on the border with Ipanem...,https://a0.muscache.com/pictures/hosting/Hosti...,Renato / Louri,18/03/2011,*French version below \r\n\r\nWe host internat...,within an hour,...,4.71,4.82,4.79,4.82,4.88,4.41,4.65,NaN,f,0.22
3,2.814590e+05,25/09/2024,Quintal da Lagoa - RefÃºgio Secreto quase Ipa...,Our apartment is the perfect choice for those ...,Lagoa is a charming neighborhood very close to...,https://a0.muscache.com/pictures/810d5101-7384...,Nilda,06/09/2011,Gosto de conhecer pessoas e novas culturas e ...,within an hour,...,5.00,4.94,5.00,5.00,5.00,4.83,4.92,NaN,f,0.51
4,2.820710e+05,25/09/2024,"Rio, hospedagem e tranquilidade",NaN,"Quiet neighbors, family building",https://a0.muscache.com/pictures/c37ed6ea-af51...,Jaqueline,04/12/2011,SimpÃ¡tica e gosto de novos amigos. Meu lazer...,within a day,...,4.68,4.80,4.76,4.80,4.83,4.77,4.60,NaN,f,0.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36962,1.250000e+18,25/09/2024,Maravilha 15,Embrace simplicity in this quiet and well-loca...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,Sara Regina De,20/01/2017,NaN,within an hour,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN
36963,1.250000e+18,26/09/2024,Sua casa na praia de Copacabana,Welcome to your getaway in Copacabana! This ap...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,Nathalia Simon,05/10/2015,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,NaN
36964,1.250000e+18,25/09/2024,Apt a 300m da praia do Recreio,Relax with the whole family in this quiet acco...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,Robert,07/08/2024,NaN,within an hour,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN
36965,1.250000e+18,25/09/2024,Casa da Dety,You will have a great time in this comfortable...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,Antonia Eridete,03/02/2024,NaN,within an hour,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,NaN
36966,1.250000e+18,25/09/2024,Apt a 300m da Praia do Recreio,Relax with the whole family in this quiet acco...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,Robert,22/05/2018,NaN,within an hour,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36967 entries, 0 to 36966
Data columns (total 50 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           36967 non-null  float64
 1   last_scraped                 36967 non-null  object
 2   name                         36967 non-null  object
 3   description                  35760 non-null  object
 4   neighborhood_overview        16949 non-null  object
 5   picture_url                  36967 non-null  object
 6   host_name                    36967 non-null  object
 7   host_since                   36967 non-null  object
 8   host_about                   17513 non-null  object
 9   host_response_time           31899 non-null  object
 10  host_response_rate           30432 non-null  float64
 11  host_acceptance_rate         31354 non-null  float64
 12  host_is_superhost            36001 non-null  object
 13  host_listings_count          36967 non-null  int64
 14  host_total_listings_count    36967 non-null  int64
 15  host_verifications           36967 non-null  object
 16  host_has_profile_pic         36967 non-null  object
 17  host_identity_verified       36967 non-null  object
 18  neighbourhood                16949 non-null  object
 19  property_type                36967 non-null  object
 20  room_type                    36967 non-null  object
 21  accommodates                 36967 non-null  int64
 22  bathrooms                    35220 non-null  float64
 23  bathrooms_text               36917 non-null  object
 24  bedrooms                     36636 non-null  float64
 25  beds                         35231 non-null  float64
 26  amenities                    36967 non-null  object
 27  price                        35223 non-null  float64
 28  minimum_nights               36967 non-null  int64
 29  maximum_nights               36967 non-null  int64
 30  calendar_updated             0 non-null      float64
 31  has_availability             36628 non-null  object
 32  availability_30              36967 non-null  int64
 33  availability_60              36967 non-null  int64
 34  availability_365             36967 non-null  int64
 35  calendar_last_scraped        36967 non-null  object
 36  number_of_reviews            36967 non-null  int64
 37  number_of_reviews_ltm        36967 non-null  int64
 38  number_of_reviews_l30d       36967 non-null  int64
 39  last_review                  28036 non-null  object
 40  review_scores_rating         28036 non-null  float64
 41  review_scores_accuracy       28035 non-null  float64
 42  review_scores_cleanliness    28036 non-null  float64
 43  review_scores_checkin        28035 non-null  float64
 44  review_scores_communication  28035 non-null  float64
 45  review_scores_location       28035 non-null  float64
 46  review_scores_value          28033 non-null  float64
 47  license                      0 non-null      float64
 48  instant_bookable             36967 non-null  object
 49  reviews_per_month            28036 non-null  float64
dtypes: float64(17), int64(11), object(22)
memory usage: 14.1+ MB

**IDENTIFICAR VALORES NULOS**

In [59]:
#Identificar valores nulos por columnas
valores_nulos=df.isnull().sum()
valores_nulos

id                                 0
last_scraped                       0
name                               0
description                     1207
neighborhood_overview          20018
picture_url                        0
host_name                          0
host_since                         0
host_about                     19454
host_response_time              5068
host_response_rate              6535
host_acceptance_rate            5613
host_is_superhost                966
host_listings_count                0
host_total_listings_count          0
host_verifications                 0
host_has_profile_pic               0
host_identity_verified             0
neighbourhood                  20018
property_type                      0
room_type                          0
accommodates                       0
bathrooms                       1747
bathrooms_text                    50
bedrooms                         331
beds                            1736
amenities                          0
price                           1744
minimum_nights                     0
maximum_nights                     0
calendar_updated               36967
has_availability                 339
availability_30                    0
availability_60                    0
availability_365                   0
calendar_last_scraped              0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
last_review                     8931
review_scores_rating            8931
review_scores_accuracy          8932
review_scores_cleanliness       8931
review_scores_checkin           8932
review_scores_communication     8932
review_scores_location          8932
review_scores_value             8934
license                        36967
instant_bookable                   0
reviews_per_month               8931
dtype: int64

In [60]:
#identificar valores nulos por dataframe

valores_nulos=df.isnull().sum().sum()
valores_nulos

239146

In [61]:
#Realizamos una copia del dataframe 

data2=df.copy()

**Sustituir valores nulos por un string en concreto**

Descripción: Las columnas que tengan entradas de texto ocupare la sustitución por un string concreto, las columnas serán 11: description, neighborhood_overview, host_about, host_response_time, host_is_superhost, neighbourhood, bathrooms_text, calendar_updated, has_availability, last_review y license. Todos los valores nulos los sustituira una leyenda que diga "SIN INFORMACION"

In [63]:
data2["description"]=data2["description"].fillna("SIN INFORMACION")
data2["neighborhood_overview"]=data2["neighborhood_overview"].fillna("SIN INFORMACION")
data2["host_about"]=data2["host_about"].fillna("SIN INFORMACIO")
data2["host_response_time"]=data2["host_response_time"].fillna("SIN INFORMACION")
data2["host_is_superhost"]=data2["host_is_superhost"].fillna("SIN INFORMACION")
data2["neighbourhood"]=data2["neighbourhood"].fillna("SIN INFORMACION")
data2["bathrooms_text"]=data2["bathrooms_text"].fillna("SIN INFORMACION")
data2["calendar_updated"]=data2["calendar_updated"].fillna("SIN INFORMACION")
data2["has_availability"]=data2["has_availability"].fillna("SIN INFORMACION")
data2["last_review"]=data2["last_review"].fillna("SIN INFORMACION")
data2["license"]=data2["license"].fillna("SIN INFORMACION")

In [64]:
valores_nulos=data2.isnull().sum()
valores_nulos

id                                0
last_scraped                      0
name                              0
description                       0
neighborhood_overview             0
picture_url                       0
host_name                         0
host_since                        0
host_about                        0
host_response_time                0
host_response_rate             6535
host_acceptance_rate           5613
host_is_superhost                 0
host_listings_count               0
host_total_listings_count         0
host_verifications                0
host_has_profile_pic              0
host_identity_verified            0
neighbourhood                     0
property_type                     0
room_type                         0
accommodates                      0
bathrooms                      1747
bathrooms_text                    0
bedrooms                        331
beds                           1736
amenities                         0
price                          1744
minimum_nights                    0
maximum_nights                    0
calendar_updated                  0
has_availability                  0
availability_30                   0
availability_60                   0
availability_365                  0
calendar_last_scraped             0
number_of_reviews                 0
number_of_reviews_ltm             0
number_of_reviews_l30d            0
last_review                       0
review_scores_rating           8931
review_scores_accuracy         8932
review_scores_cleanliness      8931
review_scores_checkin          8932
review_scores_communication    8932
review_scores_location         8932
review_scores_value            8934
license                           0
instant_bookable                  0
reviews_per_month              8931
dtype: int64

**Sustituir valores nulos por un valor numerico en concreto**

Descripción: en las columnas beds, bathrooms y bedrooms ocupare el metodo de sustitución por un numero concreto el cual será 0

In [65]:
data2["beds"]=data2["beds"].fillna(0)
data2["bathrooms"]=data2["bathrooms"].fillna(0)
data2["bedrooms"]=data2["bedrooms"].fillna(0)

In [66]:
valores_nulos=data2.isnull().sum()
valores_nulos

id                                0
last_scraped                      0
name                              0
description                       0
neighborhood_overview             0
picture_url                       0
host_name                         0
host_since                        0
host_about                        0
host_response_time                0
host_response_rate             6535
host_acceptance_rate           5613
host_is_superhost                 0
host_listings_count               0
host_total_listings_count         0
host_verifications                0
host_has_profile_pic              0
host_identity_verified            0
neighbourhood                     0
property_type                     0
room_type                         0
accommodates                      0
bathrooms                         0
bathrooms_text                    0
bedrooms                          0
beds                              0
amenities                         0
price                          1744
minimum_nights                    0
maximum_nights                    0
calendar_updated                  0
has_availability                  0
availability_30                   0
availability_60                   0
availability_365                  0
calendar_last_scraped             0
number_of_reviews                 0
number_of_reviews_ltm             0
number_of_reviews_l30d            0
last_review                       0
review_scores_rating           8931
review_scores_accuracy         8932
review_scores_cleanliness      8931
review_scores_checkin          8932
review_scores_communication    8932
review_scores_location         8932
review_scores_value            8934
license                           0
instant_bookable                  0
reviews_per_month              8931
dtype: int64

**Sustituir valores nulos con mediana**

Descripción: Para las columnas host_response_rate y host_acceptance_rate ocupare la mediana para que me de el valor de enmedio de los datos o en dado caso el promedio de los numeros sobrantes.

In [67]:
data2["host_response_rate"]=data2["host_response_rate"].fillna(round(df["host_response_rate"].median(),1))
data2["host_acceptance_rate"]=data2["host_acceptance_rate"].fillna(round(df["host_acceptance_rate"].median(),1))

In [68]:
valores_nulos=data2.isnull().sum()
valores_nulos

id                                0
last_scraped                      0
name                              0
description                       0
neighborhood_overview             0
picture_url                       0
host_name                         0
host_since                        0
host_about                        0
host_response_time                0
host_response_rate                0
host_acceptance_rate              0
host_is_superhost                 0
host_listings_count               0
host_total_listings_count         0
host_verifications                0
host_has_profile_pic              0
host_identity_verified            0
neighbourhood                     0
property_type                     0
room_type                         0
accommodates                      0
bathrooms                         0
bathrooms_text                    0
bedrooms                          0
beds                              0
amenities                         0
price                          1744
minimum_nights                    0
maximum_nights                    0
calendar_updated                  0
has_availability                  0
availability_30                   0
availability_60                   0
availability_365                  0
calendar_last_scraped             0
number_of_reviews                 0
number_of_reviews_ltm             0
number_of_reviews_l30d            0
last_review                       0
review_scores_rating           8931
review_scores_accuracy         8932
review_scores_cleanliness      8931
review_scores_checkin          8932
review_scores_communication    8932
review_scores_location         8932
review_scores_value            8934
license                           0
instant_bookable                  0
reviews_per_month              8931
dtype: int64

**Sustituir valores nulos con promedio o medio**

Descripción: Ocupe este método en 8 columnas con valores nulos: price, review_scores_accuracy, review_scores_checkin, review_scores_cleanliness, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month y review_scores_rating para que me diera los promedios y con ellos llenas los valores nulos.

In [72]:
data2["price"]=data2["price"].fillna(round(df["price"].mean(),1))
data2["review_scores_accuracy"]=data2["review_scores_accuracy"].fillna(round(df["review_scores_accuracy"].mean(),1))
data2["review_scores_checkin"]=data2["review_scores_checkin"].fillna(round(df["review_scores_checkin"].mean(),1))
data2["review_scores_cleanliness"]=data2["review_scores_cleanliness"].fillna(round(df["review_scores_cleanliness"].mean(),1))
data2["review_scores_communication"]=data2["review_scores_communication"].fillna(round(df["review_scores_communication"].mean(),1))
data2["review_scores_location"]=data2["review_scores_location"].fillna(round(df["review_scores_location"].mean(),1))
data2["review_scores_value"]=data2["review_scores_value"].fillna(round(df["review_scores_value"].mean(),1))
data2["reviews_per_month"]=data2["reviews_per_month"].fillna(round(df["reviews_per_month"].mean(),1))
data2["review_scores_rating"]=data2["review_scores_rating"].fillna(round(df["review_scores_rating"].mean(),1))

In [73]:
valores_nulos=data2.isnull().sum()
valores_nulos

id                             0
last_scraped                   0
name                           0
description                    0
neighborhood_overview          0
picture_url                    0
host_name                      0
host_since                     0
host_about                     0
host_response_time             0
host_response_rate             0
host_acceptance_rate           0
host_is_superhost              0
host_listings_count            0
host_total_listings_count      0
host_verifications             0
host_has_profile_pic           0
host_identity_verified         0
neighbourhood                  0
property_type                  0
room_type                      0
accommodates                   0
bathrooms                      0
bathrooms_text                 0
bedrooms                       0
beds                           0
amenities                      0
price                          0
minimum_nights                 0
maximum_nights                 0
calendar_updated               0
has_availability               0
availability_30                0
availability_60                0
availability_365               0
calendar_last_scraped          0
number_of_reviews              0
number_of_reviews_ltm          0
number_of_reviews_l30d         0
last_review                    0
review_scores_rating           0
review_scores_accuracy         0
review_scores_cleanliness      0
review_scores_checkin          0
review_scores_communication    0
review_scores_location         0
review_scores_value            0
license                        0
instant_bookable               0
reviews_per_month              0
dtype: int64

In [74]:
#Verificar si aún hay valores nulos por dataframe

valores_nulos=data2.isnull().sum().sum()
valores_nulos

0

In [75]:
#Convertir dataframe a csv
data2.to_csv("Rio de Janeiro_sin_nulos.csv")